version: '3.8'

services:
  backend:
    image: labsbusinessintelligence-backend:latest
    container_name: labsbi_backend_dev
    environment:
      - DB_ENGINE=mysql
      - MYSQL_HOST=72.60.140.128
      - MYSQL_PORT=33060
      - MYSQL_USER=kealabs
      - MYSQL_PASSWORD=Kea2025@!@
      - MYSQL_DATABASE=labsbi_mysql_db
      - SECRET_KEY=dev-secret-key
      - PORT=6002
      - ENVIRONMENT=dev
    ports:
      - "6002:6002"
    networks:
      - labsbi_dev

  frontend:
    image: labsbusinessintelligence-frontend:latest
    container_name: labsbi_frontend_dev
    environment:
      - REACT_APP_API_URL=http://72.60.140.128:6002
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - labsbi_dev

networks:
  labsbi_dev:
    driver: bridge